services:
  api:
    restart: unless-stopped
    environment:
      NODE_ENV: production

  web:
    restart: unless-stopped
    environment:
      NODE_ENV: production

  nginx:
    restart: unless-stopped
